controllers:
    resource: ../src/infrastructure/Controller/
    type: attribute

api_login_check:
    path: /api/login_check

redirect_home:
    path: /
    controller: Symfony\Component\HttpFoundation\RedirectResponse
    defaults:
        url: '/api/doc'